# Generated by Django 5.2.1 on 2025-05-09 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('run_number', models.CharField(max_length=20)),
                ('final_evaluation', models.BooleanField(null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('user_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('time_spent', models.CharField(blank=True, max_length=50)),
                ('levels_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
